### ISSUE TITLE
Settings reset to default after scheduler cleanup: flexforms

### ISSUE THREAD

**Issue by WSBusch** [codemacherUG/tile_proxy#3]
We have noticed a problem related to the scheduler "Execute console commands => cleanup: flexforms".
In our "tiles" page, we set the page type to "Tile Proxy Endpoint" as intended and specify our coordinates in the Tile Proxy settings.
After running the scheduler, these settings are set back to default (Raum Halle and checkbox "Pass tile outside of the bounding box" unchecked again) and our OSM is no longer visible frontend.

Can this please be checked? Thanks a lot.

TYPO3 11.5.28
PHP 7.4
TileProxy 1.1.8

**Comment by trokohl** [comment]
Hi,

at first glance it looks to me like in Typo3 Bug.
I could not reproduce the problem in Typo3 12.

The definition is:
```
 'tx_tileproxy_flexform' => [
          'label' => 'LLL:EXT:tile_proxy/Resources/Private/Language/locallang.xlf:tx_tileproxy_flexform',
          'exclude' => 1,
          'config' => [
            'type' => 'flex',
            'ds_pointerField' => 'doktype',
            'ds' => [
              Constants::DOKTYPE_TILE_PROXY => 'FILE:EXT:tile_proxy/Configuration/FlexForms/TileProxy.xml',
              Constants::DOKTYPE_NOMINATIM_PROXY => 'FILE:EXT:tile_proxy/Configuration/FlexForms/NominatimProxy.xml',
             'default' => 'FILE:EXT:tile_proxy/Configuration/FlexForms/Empty.xml',
            ],
          ],
        ],

```

So if the doktype is 601 it should use the TileProxy.xml to compare, but it use Empty.xml.

**Comment by trokohl** [comment]
How could it be otherwise, it is not a Typo3 error. The cleanup command is a little more sensitive to the flex markup.

I am building a new release, thanks for report.
