### ISSUE TITLE
OpenLayers example - JS error

### ISSUE THREAD

**Issue by ste101** [codemacherUG/tile_proxy#4]
When trying the OpenLayers example 
[OpenLayers](https://docs.typo3.org/p/codemacher/tile_proxy/main/en-us/Example/Index.html#openlayers)
I'm getting this JS error:
`Uncaught ReferenceError: L is not defined`

**Comment by trokohl** [comment]
Yes there is something mixed up.
The Leaflet example is the OpenLayer example and the other one must have the Leaflet include in it.

https://leafletjs.com/examples/quick-start/

Sorry fix it after my holidays.

**Comment by trokohl** [comment]
I quickly corrected it
