### ISSUE TITLE
noindex, nofollow

### ISSUE THREAD

**Issue by ste101** [codemacherUG/tile_proxy#5]
The tile page shows up in sitemap and has no noindex,nofollow robots tag.
What do you think would be best.
Show SEO tab with robots tag only or would it be possible to set these database fields if doctype 'Tile Proxy Endpoint' is selected?

**Comment by trokohl** [comment]
Hi,

good hint.

I think the doktype should be automatically excluded from the sitemap and get a noindex, nofollow.

I'll see how we can implement this.

**Comment by trokohl** [comment]
I have relased a news version 1.2.1, now a typoscript must be included which removes the pages from the sitemap and sets noindex nofollow.
